[functions]
  directory = "api"
  included_files = ["wp/**"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
[template.environment]
  DATABASE = "aws.connect.psdb.cloud"
  USERNAME = "hkqigren8g0ai2mn0csp"
  PASSWORD = "pscale_pw_isJfARyiySF5EaF4ohhrWzuQK9xz7GHjSsfXiSL8QXu"
  HOST = "aws.connect.psdb.cloud"
